- hosts: all
  tasks:
    - include: tasks/swap.yml
    - include: tasks/timezone.yml
    - include: tasks/essential.yml
    - include: tasks/php.yml
    - include: tasks/nginx.yml
    - include: tasks/nodejs.yml
    - include: tasks/mysql.yml
    - include: tasks/composer.yml
    - include: tasks/git.yml
  handlers:
    - include: handlers/handlers.yml
