<div class="row">
    <h1 class="col-lg-9">List of events</h1>
    <div class="col-lg-3">
        <a href="<?=$this->url('event/create')?>" class="btn btn-primary"><?=$this->translate('Create event')?></a><br /><br />
    </div>
</div>

<div class="row">
    <div class="col-lg-9">
        <?php /* @var \Application\Entity\Event $event */ ?>
        <?php foreach ($events as $event): ?>
            <div class="list-group">
                <a href="<?=$this->url('event/view', array('id' => $event->getId(), 'name' => $event->getTitle()))?>" class="list-group-item">
                <h4 class="list-group-item-heading">
                    <?php echo $this->escapeHtml($event->getTitle()) ?>
                    <small><?php echo ", ".$event->getDatetime()->format('F jS, Y \a\t H:i A') ?></small>
                    <?php
                    $user = $this->zfcUserIdentity();
                    if ($user) {
                        /** @var $rsvp \Application\Entity\RSVP */
                        foreach ($event->getRsvps() as $rsvp) {
                            if ($rsvp->getUser()->getId() != $user->getId()) {
                                continue;
                            }
                            if ($rsvp->getRsvpType() == $rsvp::TYPE_COMING) {
                                printf('<span class="label label-success">Going</span>');
                            } else {
                                printf('<span class="label label-danger">Not going</span>');
                            }
                        }
                    }
                    ?>
                </h4>

                <p class="list-group-item-text">
                    <?php echo $this->translate('Organised by:') ?><br /><br />
                    <?php echo $event->getDescription() ?>
                </p>
                <?php if ($event->getRsvps()): ?>
                    <ul class="user-list">
                    <?php foreach ($event->getRsvps() as $rsvp): ?>
                        <li>
                            <img src="http://www.gravatar.com/avatar/<?=md5($rsvp->getUser()->getEmail())?>?s=32" />
                        </li>
                        <li>
                            <img src="http://www.gravatar.com/avatar/<?=md5('rick93@gmail.com')?>?s=32" />
                        </li>
                        <li>
                            <img src="http://www.gravatar.com/avatar/<?=md5('stefan@ingewikkeld.net')?>?s=32" />
                        </li>
                        <li>
                            <img src="http://www.gravatar.com/avatar/<?=md5('jelrik@ingewikkeld.net')?>?s=32" />
                        </li>
                        <li>
                            <img src="http://www.gravatar.com/avatar/<?=md5('mike@ingewikkeld.net')?>?s=32" />
                        </li>
                    <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>
