<div class="row">
    <h1 class="col-lg-9">List of events</h1>
    <div class="col-lg-3">
        <a href="<?=$this->url('event/create')?>" class="btn btn-primary"><?=$this->translate('Create event')?></a>
    </div>
</div>

<div class="row">
    <ul class="col-lg-9 list-group">
        <?php /* @var \Application\Entity\Event $event */ ?>
        <?php foreach ($events as $event) : ?>
            <li class="list-group-item">
                <h2><?php echo $this->escapeHtml($event->getTitle()) ?></h2>
                <?php echo $event->getDatetime()->format('l F jS, Y') ?>
            </li>
        <?php endforeach ?>
    </ul>
</div>
