<?php $this->headTitle()->prepend($this->translate('Find meetspire groups')); ?>
<div class="row">
    <?php if (isset($filters['location'])): ?>
        <h1 class="col-lg-9">Meetspire groups near <?=$this->escapeHtml($filters['location'])?></h1>
    <?php else: ?>
        <h1 class="col-lg-9">View all meetspire groups</h1>
    <?php endif; ?>

    <div class="col-lg-3">
        <a href="<?=$this->url('group/create')?>" class="btn btn-primary"><?=$this->translate('Create group')?></a>
    </div>
</div>
<div class="row">
    <div class="col-lg-9">
        <ul class="list-group">
        <?php
        /** @var $group \Application\Entity\Group */
        foreach($groups as $group): ?>
            <li class="list-group-item">
                <h2><?=$this->escapeHtml($group->getName())?></h2>
                <?php if ($group->getDescription()): ?>
                    <p><?=$this->escapeHtml($group->getDescription())?></p>
                <?php else: ?>
                    <p>This meetspire group does not have a description yet</p>
                <?php endif; ?>
            </li>
        <?php endforeach ?>
        </ul>
    </div>
    <div class="col-lg-3">
        <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                Location
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <li class="presentation">
                    <a role="menuitem" tabindex="-1" href="<?=$this->url('group')?>">All locations</a>
                </li>
                <?php foreach ($locations as $location):
                    if (trim($location['location']) == '') {
                        continue;
                    }
                    ?>
                    <li class="presentation">
                        <a role="menuitem" tabindex="-1" href="<?=$this->url('group')?>?<?=http_build_query(['location' => $location['location']])?>">
                            <?php
                            if (isset($filters['location']) && $filters['location'] == $location['location']) {
                                printf('<strong>%s</strong>', $this->escapeHtml($location['location']));
                            } else {
                                echo $this->escapeHtml($location['location']);
                            }
                            ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
