<div class="row">
    <h1 class="col-lg-9">Edit Profile</h1>
</div>

<div class="row">
    <div class="col-lg-9">
        <form action="" method="POST">

        <?php foreach ($userEdit->getElements() as $element): ?>
            <?php echo $this->formRow($element); ?>
        <?php endforeach; ?>

        <div class="form-group">
            <label></label>
            <input type="submit" value="Save" class="btn btn-primary form-control" />
        </div>

        <?php echo $this->form()->closeTag($userEdit); ?>
    </div>
</div>
