<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>
<div class="row">
    <h1 class="col-lg-9"><?php echo $this->translate('Login'); ?></h1>
</div>

<div class="row">
    <div class="col-lg-9">
        <form action="<?php echo $this->url('zfcuser/login') ?>" method="POST">

            <?php echo $this->formElementErrors($form->get('identity')) ?>

            <?php echo $this->formRow($form->get('identity')) ?>

            <?php echo $this->formRow($form->get('credential')) ?>

            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
            <?php endif ?>

            <div class="form-group">
                <label></label>
                <?php echo $this->formButton($form->get('submit')) ?>
            </div>

        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

<?php if ($this->enableRegistration) : ?>
    <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>
